#!/bin/bash
#------------------------------------------------------------------------------
# License
#     This file is part of spaceTime4foam, licensed under GNU General Public
#     License <http://www.gnu.org/licenses/>.
#
# Script
#     applications/test/Allwclean
#
# Description
#     Clean every application in this directory that has a Make directory.
#
#------------------------------------------------------------------------------
cd "${0%/*}" || exit  # Run from this directory

for app in */
do
    app="${app%/}"
    if [ -d "$app/Make" ]
    then
        wclean "$app"
    fi
done

#------------------------------------------------------------------------------
